#!/bin/bash 

# Get a list of all user accounts 
users=$(awk -F':' '{if ($3 >= 1000 && $1 != "nobody") print $1}' /etc/passwd)  

# Prompt the user to enter the new password  

read -p "Enter the new password: " new_password  

# Loop through each user and change the password  

for user in $users  

do  

echo -e "$new_password\n$new_password" | passwd $user  

echo "Password changed for user: $user"  

done  

echo "Password change process completed." 
